### ISSUE TITLE
Update Readme: gem 'sms_spec'

### ISSUE THREAD

**Issue by threadhead** [mhs/sms-spec#1]
gem 'sms_spec' should be gem 'sms-spec'

**Comment by manlycode** [comment]
Thanks for the catch Karl. I'll update this as soon as I can.

## 

Chris Rittersdorf
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jeremywrowe** [comment]
This has been taken care of in the newest release.
