### ISSUE TITLE
'undefined method .sid' error

### ISSUE THREAD

**Issue by jpwynn** [mhs/sms-spec#3]
in my existing twilio code, I authenticate that the twilio account posting a message to my app is in fact 'my' account (a twilio-recommended security precaution) by comparing the posted SID with my app's SID via: 

if (params[:AccountSid] == client.account.sid)
... do stuff with message

Works great in dev and production and staging.

But it looks like the magic you do to replace the twilio params doesn't know about the .sid method because when running in rspec my app throws an undefined method error.

it was easy to stub out for test:

if (ENV['RAILS_ENV'] == 'test') || (params[:AccountSid] == client.account.try(:sid))

And you may wish to add that to your README unless/until you add the .sid method..

Awesome work on the gem BTW - very cool.

**Comment by jeremywrowe** [comment]
Thanks @jpwynn I will be taking a look at the issue this afternoon.

**Comment by jeremywrowe** [comment]
The issue has been updated in the newest version of the gem I am closing the issue.
